server:
  port: 8989
spring:
  application:
    name: GATEWAY-SERVICE

  config:
    import: configserver:http://localhost:9196

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**

logging:
  file:
    name: D:/Qualigytech-Springboot/elk_logs_folder/microservices_elk_logs.log
# traceID and spanId are predefined MDC keys - we want the logs to include them
pattern:
  console: "%p [%%X{traceId:-},%%X{spanId:-}] [%%t] --- %%c{1}.%%M:%%L - %%m%%n"
management:
  tracing:
    sampling:
      probability: 1.0
